import PDFDocument from "pdfkit";

export interface InvoiceLineItem {
  name: string;
  price: number;
}

export interface InvoiceData {
  invoiceNumber: string;
  salonName: string;
  clientName: string;
  clientPhone: string;
  items: InvoiceLineItem[];
  paymentMode: string;
  issuedAt: Date;
}

export function generateInvoicePdf(data: InvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A5", margin: 40 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).text(data.salonName, { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#666").text(`Invoice #${data.invoiceNumber}`, { align: "center" });
    doc.text(data.issuedAt.toLocaleString(), { align: "center" });
    doc.moveDown();

    doc.fillColor("#000").fontSize(11);
    doc.text(`Client: ${data.clientName}`);
    doc.text(`Phone: ${data.clientPhone}`);
    doc.moveDown();

    doc.font("Helvetica-Bold");
    doc.text("Service", 40, doc.y, { continued: true, width: 260 });
    doc.text("Price (LKR)", { align: "right" });
    doc.font("Helvetica");
    doc.moveDown(0.3);
    doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
    doc.moveDown(0.3);

    let total = 0;
    for (const item of data.items) {
      total += item.price;
      doc.text(item.name, 40, doc.y, { continued: true, width: 260 });
      doc.text(item.price.toFixed(2), { align: "right" });
    }

    doc.moveDown(0.5);
    doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
    doc.moveDown(0.3);

    doc.font("Helvetica-Bold");
    doc.text("Total", 40, doc.y, { continued: true, width: 260 });
    doc.text(`LKR ${total.toFixed(2)}`, { align: "right" });
    doc.font("Helvetica");
    doc.moveDown();
    doc.fontSize(10).fillColor("#666").text(`Payment mode: ${data.paymentMode}`);

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#999").text("Generated by GlamEdge Studio Engine", { align: "center" });

    doc.end();
  });
}
