-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('BOOKING_REQUESTED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW_THANKS', 'INVOICE_READY', 'RESCHEDULE_PROPOSED', 'RESCHEDULE_ACCEPTED', 'RESCHEDULE_DECLINED', 'NEW_MESSAGE', 'REVIEW_SUBMITTED') NOT NULL;

-- AlterTable
ALTER TABLE `owner_notifications` MODIFY `type` ENUM('BOOKING_REQUESTED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW_THANKS', 'INVOICE_READY', 'RESCHEDULE_PROPOSED', 'RESCHEDULE_ACCEPTED', 'RESCHEDULE_DECLINED', 'NEW_MESSAGE', 'REVIEW_SUBMITTED') NOT NULL;
