-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('BOOKING_REQUESTED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW_THANKS', 'INVOICE_READY', 'RESCHEDULE_PROPOSED', 'RESCHEDULE_ACCEPTED', 'RESCHEDULE_DECLINED', 'NEW_MESSAGE', 'REVIEW_SUBMITTED', 'SUBSCRIPTION_EXPIRING', 'SUBSCRIPTION_EXPIRED') NOT NULL;

-- AlterTable
ALTER TABLE `owner_notifications` MODIFY `type` ENUM('BOOKING_REQUESTED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW_THANKS', 'INVOICE_READY', 'RESCHEDULE_PROPOSED', 'RESCHEDULE_ACCEPTED', 'RESCHEDULE_DECLINED', 'NEW_MESSAGE', 'REVIEW_SUBMITTED', 'SUBSCRIPTION_EXPIRING', 'SUBSCRIPTION_EXPIRED') NOT NULL;

-- AlterTable
ALTER TABLE `tenants` ADD COLUMN `approvedAt` DATETIME(3) NULL,
    ADD COLUMN `expiryNotifiedAt` DATETIME(3) NULL,
    ADD COLUMN `rejectionReason` VARCHAR(500) NULL,
    ADD COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `subscriptionCycle` ENUM('MONTHLY', 'YEARLY') NOT NULL DEFAULT 'MONTHLY',
    ADD COLUMN `subscriptionExpiresAt` DATETIME(3) NULL,
    ADD COLUMN `subscriptionStartedAt` DATETIME(3) NULL;

-- CreateTable
CREATE TABLE `admins` (
    `id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `passwordHash` VARCHAR(255) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `admins_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
