#!/usr/bin/env bash
#
# One-time setup for the EC2 box. Run it ON THE SERVER, once, before the first
# GitHub Actions deploy:
#
#   curl -fsSL https://raw.githubusercontent.com/warnasooriya/GlamEdge-Studio-Engine/main/scripts/server-bootstrap.sh | bash
#
# or copy this file across and run it. It is safe to re-run: an existing .env is
# never overwritten, so your secrets and database credentials survive.
#
# What it does NOT do: install Docker (already present), open security-group
# ports (do that in the AWS console), or start the app (the deploy does that).
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/glamedge}"

echo "==> Checking Docker"
if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is not installed or not on PATH." >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "error: the Docker Compose v2 plugin is missing." >&2
  echo "       Install it with: sudo apt-get install -y docker-compose-plugin" >&2
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo "error: cannot talk to the Docker daemon as $(id -un)." >&2
  echo "       Fix with: sudo usermod -aG docker $(id -un)  (then log out and back in)" >&2
  exit 1
fi
echo "    docker $(docker --version | awk '{print $3}' | tr -d ,), compose $(docker compose version --short)"

echo "==> Creating $DEPLOY_DIR"
if [ ! -d "$DEPLOY_DIR" ]; then
  sudo mkdir -p "$DEPLOY_DIR"
  sudo chown "$(id -u):$(id -g)" "$DEPLOY_DIR"
fi
mkdir -p "$DEPLOY_DIR/nginx"

cd "$DEPLOY_DIR"

if [ -f .env ]; then
  echo "==> .env already exists — leaving it untouched"
else
  echo "==> Writing .env with a generated JWT_SECRET"
  # Public IPv4 of this instance, so PUBLIC_URL is right without being told.
  PUBLIC_IP="$(curl -fsS --max-time 5 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)"
  [ -z "$PUBLIC_IP" ] && PUBLIC_IP="$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo 'CHANGE_ME')"

  JWT="$(openssl rand -base64 48 | tr -d '\n')"
  MYSQL_PW="$(openssl rand -base64 24 | tr -d '\n/+=')"
  MYSQL_ROOT_PW="$(openssl rand -base64 24 | tr -d '\n/+=')"

  cat > .env <<EOF
# Generated by server-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Deploys never overwrite this file. Restart after editing:
#   cd $DEPLOY_DIR && docker compose up -d

# --- Where the app is reachable ---------------------------------------------
# No domain yet, so this is the bare IP over HTTP. Once DNS points at this box,
# see DEPLOYMENT.md "Enabling HTTPS" — it is a three-line change plus one script.
DOMAIN=$PUBLIC_IP
NGINX_TEMPLATE=http
PUBLIC_URL=http://$PUBLIC_IP

# --- Certbot (only used once you have a real domain) ------------------------
CERTBOT_EMAIL=
CERTBOT_STAGING=1

# --- Secrets ------------------------------------------------------------------
JWT_SECRET=$JWT
JWT_EXPIRES_IN=7d

# First admin, created on first boot only. With the password left blank, one is
# generated and printed to the API logs:
#   docker compose logs api | grep -A3 "First admin"
ADMIN_EMAIL=admin@glamedge.dev
ADMIN_PASSWORD=

# --- Datastores ---------------------------------------------------------------
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PW
MYSQL_DATABASE=glamedge
MYSQL_USER=glamedge
MYSQL_PASSWORD=$MYSQL_PW
MONGO_DATABASE=glamedge_feed

# Bound to 127.0.0.1 by compose — reachable only via SSH tunnel, not publicly.
MYSQL_HOST_PORT=3307
MONGO_HOST_PORT=27017
REDIS_HOST_PORT=6379

# --- OTP delivery -------------------------------------------------------------
# "console" prints login codes to the API logs. Switch to notifylk for real SMS.
OTP_PROVIDER=console
NOTIFYLK_USER_ID=
NOTIFYLK_API_KEY=
NOTIFYLK_SENDER_ID=

# --- Media storage ------------------------------------------------------------
# Blank = uploads live on the api_uploads Docker volume. Set all four to use S3.
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=ap-southeast-1
AWS_S3_BUCKET=
AWS_CLOUDFRONT_URL=

# --- WhatsApp Cloud API -------------------------------------------------------
WHATSAPP_CLOUD_API_TOKEN=
WHATSAPP_PHONE_NUMBER_ID=

# --- Set by CI on each deploy; do not edit by hand ---------------------------
EOF
  chmod 600 .env
  echo "    generated JWT_SECRET and database passwords"
  echo "    PUBLIC_URL=http://$PUBLIC_IP"
fi

echo
echo "Bootstrap complete. $DEPLOY_DIR is ready."
echo
echo "Next:"
echo "  1. Add these repository secrets on GitHub"
echo "     (Settings -> Secrets and variables -> Actions):"
echo "        EC2_HOST      $(curl -fsS --max-time 5 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo '<this server IP>')"
echo "        EC2_USER      $(id -un)"
echo "        EC2_SSH_KEY   the private key you SSH in with"
echo "  2. Make sure the security group allows inbound 80 (and 443 for HTTPS)."
echo "  3. Push to main — the workflow builds, pushes, and deploys."
